"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.VERIFICATIONTOKENEXPIRYTIME = exports.APPURL = exports.APPNAME = exports.NANOIDLENGTH = void 0;
var NANOIDLENGTH = 8;
exports.NANOIDLENGTH = NANOIDLENGTH;
var APPNAME = "";
exports.APPNAME = APPNAME;
var APPURL = "";
exports.APPURL = APPURL;
var VERIFICATIONTOKENEXPIRYTIME = 600;
exports.VERIFICATIONTOKENEXPIRYTIME = VERIFICATIONTOKENEXPIRYTIME;
